---
title: "CartoPneu"
author: "Ibrahima SOW"
date: "12/14/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
library(data.table)
library(stringr)
getwd()
```


```{r}
sensor_1_P1 <- fread("P1/sensor_1.csv", header = F, quote = "")
names(sensor_1_P1)[1] <- "sensor_id"
names(sensor_1_P1)[2] <- "sensor_time"
names(sensor_1_P1)[3] <- "value"
``` 

```{r}
sensor_2_P1 <- fread("P1/sensor_2.csv", header = F, quote = "")
names(sensor_2_P1)[1] <- "sensor_id"
names(sensor_2_P1)[2] <- "sensor_time"
names(sensor_2_P1)[3] <- "value"
``` 

```{r}
sensor_1_P1$sensor_id <- substr(sensor_1_P1$sensor_id, 14, 14)
sensor_2_P1$sensor_id <- substr(sensor_2_P1$sensor_id, 14, 14)

sensor_1_P1$sensor_time <- substr(sensor_1_P1$sensor_time, 16, 38)
sensor_2_P1$sensor_time <- substr(sensor_2_P1$sensor_time, 9, nchar(sensor_2_P1$sensor_time)-2)

sensor_1_P1$value <- substr(sensor_1_P1$value, 10, 13)
sensor_2_P1$value <- substr(sensor_2_P1$value, 10, 13)

sensor_2_P1$value <- gsub("\"", "", sensor_2_P1$value)
sensor_2_P1$value <- gsub("}", "", sensor_2_P1$value)

sensor_1_P1$sensor_time <- gsub("T", " ", sensor_1_P1$sensor_time)
#sensor_1_P1$sensor_time <- gsub("Z", "", sensor_1_P1$sensor_time)

sensor_2_P1$sensor_time <- gsub("T", " ", sensor_2_P1$sensor_time)
#sensor_2_P1$sensor_time <- gsub("Z", "", sensor_2_P1$sensor_time)
```

```{r}
# Binding P1s
mydata_p1 <- rbind(sensor_1_P1, sensor_2_P1)
mydata_p1
```

```{r}
mydata_p2 <- fread("P2/sensor_1.csv", header = F, quote = "")
names(mydata_p2)[1] <- "sensor_id"
names(mydata_p2)[2] <- "sensor_time"
names(mydata_p2)[3] <- "value"
mydata_p2
``` 


```{r}
mydata_p2$sensor_id <- substr(mydata_p2$sensor_id, 14, 14)

mydata_p2$sensor_time <- substr(mydata_p2$sensor_time, 16, 34)
mydata_p2$sensor_time <- gsub("T", " ", mydata_p2$sensor_time)

mydata_p2$value <- substr(mydata_p2$value, 10, 14)

mydata_p2$value <- gsub("\"", "", mydata_p2$value)
mydata_p2$value <- gsub("}", "", mydata_p2$value)

#sensor_1_P2$sensor_time <- gsub("Z", "", sensor_1_P2$sensor_time)
head(mydata_p2)
```

## Importing simple log files 

```{r message=FALSE, warning=FALSE}
#simple_log_P1 <- fread("P1/simple-log.txt",  header = F)
simple_log_P2 <- fread("P2/simple-log.txt",  header = F)

#simple_log_P1$V1 <- substr(simple_log_P1$V1, 1, 23)
simple_log_P2$V1 <- substr(simple_log_P2$V1, 1, 19)


names(simple_log_P2)[1] <- "date_time"
names(simple_log_P2)[2] <- "date_gnss"
names(simple_log_P2)[3] <- "heure_gnss"
names(simple_log_P2)[4] <- "latitude"
names(simple_log_P2)[5] <- "longitude"
names(simple_log_P2)[6] <- "speed"
simple_log_P2
```


```{r}
logs <- simple_log_P2[!is.na(simple_log_P2$latitude) &
                                 !is.na(simple_log_P2$longitude), ] %>%
        subset(select = -c(date_gnss, heure_gnss))
logs
```

```{r}
# Binding by date_time

#While date_time < à la valeur associée 
# parcourir capteurs file et while que la date du fichier captreur est inférieur à la 
#ifelse(strptime(mydata_p2$sensor_time[1], "%H:%M") < strptime(simple_log$date_time[1], "%H:%M"), "Dead", "NONE")

mydata_p2$sensor_time <- as.POSIXct(mydata_p2$sensor_time)
logs$date_time <- as.POSIXct(logs$date_time)

# names(mydata_p2)[2] <- "date_time"
# df_p1 <- merge(simple_log_P1, mydata_p1, by="date_time")
# table(df_p1$value)

# j=1
# for (i in 1:length(sensor_clean[,1])){
#   print(i)
#   while (sensor_clean$time[i]>simple_log$time[j]) {
#     j=j+1
#   }
#   sensor_clean$associate=j
# }
df2 <- mydata_p2
df2$value <- as.numeric(df2$value)
```

```{r}
df2 %>%
  group_by(sensor_time) %>%
  summarise_each(median, value)
```

```{r}
sensor <- aggregate(as.numeric(mydata_p2$value),
                    by=list(mydata_p2$sensor_time),
                    data=mydata_p2,FUN=median)
```

```{r}
#mydata_p2X <- unique(mydata_p2)

for (i in 1:nrow(sensor)){
  
  if(sensor$sensor_time[i] == logs$date_time[i]){
    
     sensor$lat[i] <- logs$latitude[i]
     sensor$long[i] <- logs$longitude[i]
     sensor$long[i] <- logs$speed[i]
     print(i)
}
}
#length(unique(simple_log$date_time))
```


```{r}
names(sensor)[1] <- "date_time"
mydf <- merge(sensor, logs, by="date_time")
names(mydf)[2] <- "value"
dim(mydf)
```

```{r}
for (i in 1:nrow(mydf)) {
    map$marker(c(mydf[i, "latitude"], mydf[i, "longitude"]), bindPopup = mydf[i, "location"])
}
```


```{r}
library(leaflet)
map <- leaflet(mydf) %>% addProviderTiles(providers$CartoDB.DarkMatterNoLabels,
                      options = providerTileOptions(noWrap = TRUE)) %>%
       addMarkers()
map
```

### Plot_ly 
```{r}
library(plotly)
```

```{r}
fg <- plot_ly(x=~mydf$date_time, y=mydf$value, alpha = 0.4,
              mode = 'markers', text = paste("days from today"))
fg
```

```{r message=FALSE, warning=FALSE}
my_parcelles <- read_csv("P2/GIS_parcelles.csv");my_parcelles
roads <- read_csv("P2/GIS_routes.csv");roads
mydf
```

```{r}
names(my_parcelles)[1] <- "date_time"
names(roads)[1] <- "date_time"
  
names(my_parcelles)[2] <- "date_gnss"
names(roads)[2] <- "date_gnss"
  
names(my_parcelles)[3] <- "time_gnss"
names(roads)[3] <- "time_gnss"
table(my_parcelles$`ID Culture`)
roads
```

```{r}
mydf$date_time <- as.character(mydf$date_time)
my_parcelles$date_time <- as.character(my_parcelles$date_time)
```

```{r}
join_parcelles <- merge(mydf, my_parcelles, by="date_time")
table(join_parcelles$`ID Culture`)
```



```{r}
join_parcelles$date_time <- as.POSIXct(join_parcelles$date_time)

fg <- plot_ly(x=~join_parcelles$date_time, y=~join_parcelles$value, alpha = 0.4,
              colors = ~join_parcelles$`ID Culture`,
              mode = 'markers', text = paste("days from today"))
fg
```

