---
title: "Flexi Pneus"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    favicon: "flavicon.jpeg"
    source_code: embed
    theme: spacelab
    css: netflex_lightened.css
    social: "menu" 
    vertical_layout: fill
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
# Packages loading. 
library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyjs)
library(shinyBS)
library(shinyLP)
library(shinycssloaders)
library(shinybusy)
library(shinyjs)
library(flexdashboard)
library(vov)
library(leaflet)
library(viridis)
library(shinyWidgets)
library(waiter)
library(htmltools)
library(tidyverse)
library(readr)
library(data.table)
library(stringr)
```


```{r global, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Data loading 
# 2nd passage
sensor_df <- fread("sensor_df.csv", header = T) %>% subset(select = -(V1))
options(digits.secs = 3) 
# sensor_df$sensor_time <- as.POSIXct(sensor_df$sensor_time)
# sensor_df$value <- as.numeric(sensor_df$value)
```


```{r}
## Main dataset 
mydata <- read.csv("netflex5.csv")
mydata$Show_type[is.na(mydata$Show_type)] <- 'undefined'
mydata$Genre[is.na(mydata$Genre)] <- 'undefined'
```


#  Home Page {data-orientation=rows}     

Row 
-------------------------------------

```{r} 
# Busy bar for UX enhancement 
add_busy_bar(timeout = 400, color = "#c7636a", centered = FALSE, height = "6px")
# Background image adding. Origin : https://hcdevilsadvocate.com/ae/2019/01/25/best-new-netflix-releases-to-binge-during-the-cold-weather/
tags$img(
     src = "img/carto_pneu.jpg", 
     style = 'position: fixed'
   )
```

### ValBox {data-height=800}

```{r}
# Disclaimer : The following jumbotron function is an adpatation of Jumbotron() from the shinyLP package (Copyright holder : Jasmine Dumas // https://github.com/cran/shinyLP). We adapted it  to receive a btn link and enhanced the rendering.

# Jumbotron 
## Jumbotron function for Landing page 
my_jumbotron <- function(header , content, button = TRUE, button_link, ...){
  
  button_label = c(...)
  if (button){
    div(class = "jumbotron",
        h1(header), p(content), p(a(href = button_link ,target="_blank",
        class = "btn btn-primary btn-lg button", role= 'button', button_label)))
} else {
    div(class = "jumbotron", h1(header), p(content))
}
  
}

## Fixed landing page fading in, with a btn link to our github reporsitory 
fixedPage(
use_vov(),
    fade_in_up(
my_jumbotron(header="Welcome to Flexi Pneus", content="Please call attention to important features of the app", button =  "True", button_link="https://github.com/sow-ibrahima/tech_challenge", button_Label = "Check our repo'"))
)
```


Row {data-height=150}
-------------------------------------

Row 
-------------------------------------
```{r}
# Empty row like this help better organize the landing page 
```

### Profiles
```{r}
# ValueBox displaying the number of unique profiles used in our app 
renderValueBox({

valueBox(
                tags$p(length(unique(mydata$Profile)),
                style = "font-size: 200%; color:	#FFFFFF;"),
                tags$q("Netflix Profiles",style = "font-size: 150%; color:	#FFFFFF;"),
                icon ="fa-users",color = "green")

})
```


### Movies seen
```{r}
# ValueBox displaying the number of movies seen by profiles in our app 
renderValueBox({
  
valueBox(
                tags$p(table(mydata$Show_type=="movie")[2],
                style = "font-size: 200%; color:	#FFFFFF;"),
                tags$q("Movies seen",style = "font-size:150%; color:	#FFFFFF;"),
                icon ="fa-video", color = "orange")

})
```

### Series seen
```{r}
# ValueBox displaying the number of series seen by profiles in our app 
renderValueBox({
  
valueBox(
                tags$p(table(mydata$Show_type=="series")[2],
                style = "font-size: 200%; color:#FFFFFF;"),
                tags$q("Series seen",style = "font-size: 150%; color:	#FFFFFF;"),
                icon ="fa-film", color="red")

  })
```

Row
-------------------------------------
```{r}
```

# Explanatory visualization {data-orientation=column}
## Input {.sidebar}

```{r}
selectInput("road_X", "Please choose a section", c("Section_1", "Section_2", "Section_3", "total_parcours"))

sliderInput("obs", "Number of observations:",
    min = 10, max = 30000, value = 10000)

# sliderInput("timeRange", label = "Time range",
#                    min = as.POSIXct("2011-06-04 12:00:00"),
#                    max = as.POSIXct("2011-08-10 14:00:00"),
#                    value = c(as.POSIXct("2011-06-04 12:00:00"),
#                              as.POSIXct("2011-08-10 14:00:00")))

radioButtons(
  "mode",
  "Please choose a drawing mode",
  choices = c("markers", "lines")
)

actionButton("update", "Update range")


```

## Column {.tabset}

### Roads mapping

```{r message=FALSE, warning=FALSE}
library(viridis)
library(leaflet)


renderLeaflet({
road_X <- read.csv(paste0(as.character(input$road_X),".csv"))

#read_csv(paste0(input$road_X,".csv"))

domain <- range(road_X$value)

# make palette
pal <- colorNumeric(palette = viridis(3), domain = domain)

leaflet(road_X) %>%
                addProviderTiles(providers$CartoDB.DarkMatterNoLabels,
                options = providerTileOptions(noWrap = TRUE)) %>%
                setView(lat=43.5398,lng=3.8607, 14.5) %>%
                addCircleMarkers(radius = ~(value-350), color = ~pal(value),
                                fillColor = ~pal(value), opacity = 0.2,
                                label = paste0(road_X$value, " - ",road_X$sensor_time))
})
```

### Fields mapping

```{r message=FALSE, warning=FALSE}
library(viridis)
library(leaflet)
library(raster)
library(rgdal)

renderLeaflet({

myfields <- read_csv("myfields.csv") %>% subset(select = -c(X1))

domain <- range(myfields$value)
soil_rasters <- raster("classif_sol.tif",prefer_proj = epsg3857)
# make palette

myfields$lat <- as.numeric(myfields$lat)
myfields$long <- as.numeric(myfields$long)
pal <- colorNumeric(palette = viridis(3), domain = domain)
rasters_pal <- colorNumeric(c("#43A9F2", "#F1D674", "#F46C6A"), values(soil_rasters),na.color = "transparent")


parcellaire <- readOGR("P2/Parcellaire_chapitre/Culture attributs.shp")

larzats <- parcellaire[parcellaire$Parcella_1=="Larzat",] %>% spTransform(CRS("+proj=longlat +datum=WGS84"))
factpal2 <- colorFactor(viridis(2, option = "magma", direction = -1), larzats$ID.Culture, reverse = T)

# lat=43.5483,lng=3.8437, 17 parcelles

leaflet(myfields) %>%
                addProviderTiles(providers$CartoDB.DarkMatterNoLabels,
                      options = providerTileOptions(noWrap = TRUE),  group = "Basic Layer(default)") %>%
                setView(lat=43.5483,lng=3.8437, 17) %>%

                leaflet::addPolygons(data=larzats,stroke=TRUE,color = "white",
                                     fillColor = ~factpal2(larzats$ID.Culture), opacity = 1,
                                     group = "Parcellaire") %>%

                addCircleMarkers(lng = ~long, lat = ~lat,radius = ~(value-350), color = ~pal(value),
                        fillColor = ~pal(value), opacity = 0.2,
                        label = paste0(myfields$value, " - " ,myfields$soil_type), group = "Values") %>%

                addRasterImage(soil_rasters, colors = rasters_pal, opacity = 0.8, group = "Soil types") %>%

                addLegend(position = "topright",colors = c("#43A9F2", "#F1D674", "#F46C6A"),
                         labels = c("Argileux","Moyen","Caillouteux"), opacity = 0.8,title = "Soil type classification",
                          group = "Soil types") %>%
                addLayersControl(baseGroups = c("Basic Layer (default)"),
                                 overlayGroups = c("Values","Soil types", "Parcellaire"),
                                 position = "topleft",options = layersControlOptions(collapsed = T)
  )
})
```

### Temporal series plotting
```{r}
library(plotly)
plotly::renderPlotly({
road_X <- read.csv(paste0(as.character(input$road_X),".csv"))

# road_X <- read.csv("Section_1.csv")

plot_ly(road_X[1:as.numeric(input$obs), ], x=~as.POSIXct(sensor_time), y=~as.numeric(value), alpha = 0.4,
                mode = input$mode, color = ~observations)
 })
```

# Analysis {data-orientation=column}
## Input {.sidebar}

## Column {.tabset}

### Temporal viz 
### Temporal viz 
### Temporal viz 
# Data sources {data-orientation=column}
Row {.tabset}
-------------------------------------
### Main data source 